tickers_techs = ['UPWK', 'APPS', 'NFLX', 'SNAP', 'ISRG', 'SQSP', 'ZG', 'BE',
                 'SEDG', 'WIX', 'FSLR', 'TSLA', 'SSTK', 'PSN', 'APP', 'BYND',
                 'ADBE', 'QRVO', 'JNPR', 'PINS', 'NVDA', 'PLTR', 'FISV', 'FSLY',
                 'RPD', 'NET', 'ANET', 'VMW', 'AEIS', 'TTD', 'AKAM', 'ORCL', 
                 'DOCN', 'FTNT', 'CRM', 'QLYS', 'V', 'SPLK', 'TTWO', 'ANSS',
                 'U', 'TDC', 'RKLB', 'PANW', 'PYPL', 'COUP', 'SONY', 'SNPS', 
                 'STX', 'DT', 'FORM', 'SWKS', 'SHOP', 'MA', 'ADSK', 'PLUG', 
                 'AZPN', 'AMD', 'SDGR', 'ZM', 'EPAM', 'ONTO', 'TREX', 'ABNB', 
                 'CRWD', 'BKI', 'LRCX', 'CGNX', 'MDB', 'INTC', 'NOW', 'ASGN', 
                 'PAYC', 'TWLO', 'PSA', 'APPN', 'DISH', 'BMBL', 'PTON', 'HOOD', 
                 'DLR', 'ROKU', 'GTLB', 'COIN', 'UPST', 'IT', 'ETSY', 'SPT', 
                 'PSTG', 'OKTA', 'ASAN', 'AAPL', 'MSFT', 'AMZN', 'PRGS', 'SQ',
                 'SNOW', 'ZS', 'HUBS', 'KEYS', 'AYX', 'TXN', 'DELL', 'GRMN',
                 'ADI', 'MU', 'CIEN', 'DIOD', 'QCOM', 'IBM', 'AMAT', 'DBX',
                 'RBLX', 'ESTC', 'MSTR', 'RIOT', 'AI'
                ]

tickers_sc = ["MVIS", "KOPN", "QNST", "TLS", "APEI", "EGHT", "BLMN", "INSG", "AOSL",
              "WW", "CPS", "MLNK", "FNKO", "NABL", "OFIX", "PNTG", "HEAR", "VUZI",
              "UCTT", "BJRI", "ZUO", "FARO", "TTMI", "COHU", "EAT", "VPG", "FLWS",
              "PUBM", "ANDE", "WISH", "BH", "ATGE", "CVGW", "PETQ", "ARRY", "NSSC",
              "CNXN", "CCSI", "TWOU", "SFIX", "CRMT", "SPNS", "MHO", "GPRO", "CEVA",
              "ATEX", "PI", "SHEN", "VMEO", "YEXT", "PLUS", "MCRI", "SCSC", "ASTS",
              "SKLZ", "XNCR", "MEI", "WGO", "MSEX", "RELY", "CRNC", "BLNK", "CGNT",
              "SLP", "LPSN", "ATNI", "GTX", "IDCC", "MGPI", "ZUMZ", "HZO", "UDMY",
              "ATEN", "MED", "BIGC", "AAN", "MOV", "DRQ", "AOUT", "NTGR", "DLTH",
              "JBSS", "BZUN", "POSH", "RGR", "MFGP", "SUMO", "VLDR", "DM", "VERU",
              "LRN", "RCII", "GES", "FTCI", "JOUT", "EPC", "WKHS", "GCO", "BGS", "CLSK",
              "QUOT", "USNA", "ANAB", "TAL", "ETD", "OSIS", "THS", "XPEL", "CHEF",
              "JACK", "SBH", "MBUU", "STRA", "SLVM", "EVBG", "BAND", "UTL", "CARS",
              "AMCX", "ANF", "PRTS", "IRBT", "BIG", "HIBB", "APPH", "HCC", "VZIO",
              "LEGH", "METC", "WWW", "OSTK", "MOMO", "HYLN", "MNRO", "SNBR", "SOHU",
              "CDLX", "STEM", "PLCE", "QRTEA", "TTCF"
             ]

tickers_schealth = ['QNCX', 'GOSS', 'TCMD', 'BDTX', 'AXGN', 'BBIO', 'AUPH', 'RCUS',
                   'SKIN', 'ATRI', 'SRDX', 'NVRO', 'AMTI', 'ADPT', 'CYRX', 'ADUS',
                   'BCRX', 'ZYXI', 'HSKA', 'ANIK', 'VNDA', 'AMPH', 'EGRX', 'EAR',
                   'MLAB', 'ESPR', 'IRWD', 'CGEN', 'AVNS', 'MYGN', 'AWH', 'TCRR',
                   'MODV', 'ARCT', 'EMBC', 'CVM', 'HCAT', 'INVA', 'NVAX', 'AORT',
                   'FLGT', 'USPH', 'RETA', 'CSII', 'MDRX', 'AERI', 'KDNY', 'SDGR',
                   'EBS', 'GRPH', 'VREX', 'VCEL', 'MD', 'CHRS', 'TVTX', 'NVTA',
                   'RGNX', 'KIDS', 'NRIX', 'INGN', 'TWST', 'VCYT', 'HIMS', 'ALEC',
                   'ZYNE', 'ALXO', 'BLUE', 'VXRT', 'BNGO', 'ZIMV', 'FATE', 'CDNA',
                   'ORMP', 'MRVI', 'LGND', 'ANIP', 'ENTA', 'ATRA', 'CLOV', 'LYEL',
                   'BTAI', 'DMTK', 'RYTM', 'KOD', 'AGIO', 'NEO', 'TSVT', 'ARQT', 
                   'SAVA', 'AVXL', 'DCPH', 'ALLO', 'FULC', 'ZNTL', 'OSUR', 'TRHC',
                   'RXRX', 'CARA', 'SLDB', 'EDIT', 'ARVN', 'INO', 'APLT', 'ICPT',
                   'IGMS', 'AFMD', 'BYSI', 'SWTX', 'IOVA', 'GTHX', 'ALLK', 'SGMO',
                   'HRTX', 'AVIR', 'PRAX', 'NKTR', 'ALT'
                    ]

tickers_energy = ["COP", "SR", "SWX", "CEG", "OGS", "VST", "NFE", "SWN",
                  "VTNR", "BE", "LNG", "OGE", "AMR", "MPC", "ENB", "ET",
                  "ARCH", "TRGP", "EQT", "CTRA", "OKE", "WMB", "CCJ", "ETRN",
                  "ENPH", "SJI", "KMI", "AM", "OVV", "INT", "PSX", "PBA",
                  "TTE", "VLO", "VET", "CLR", "SHEL", "XOM", "CNQ", "CVX",
                  "PDS", "REX", "MGY", "CNX", "PXD", "APA", "EOG", "HES",
                  "BLDP", "OXY", "PBF", "FTI", "SU", "PDCE", "FCEL", "UUUU",
                  "OII", "MRO", "HAL", "HP", "DK", "NOV", "PUMP", "GEVO",
                  "DVN", "CHX", "SLB", "RIG", "BKR", "WHD", "VAL", "OIS",
                  "CLB", "WTTR", "FANG", "MUR"
                 ]

tickers_commodity_stocks = ["KALU", "CE", "EXP", "ASIX", "CC", "EMN", "SRI", "DD", "SMG", "OI", "ALB", 
                            "ATI", "LAC", "BCC", "MTRN", "KWR", "NTR", "MTX", "X", "PPG", "OLN", "CMC",
                            "CBT", "SHW", "FCX", "AA", "AXTA", "CMP", "LYB", "MATV", "CLF", "WLK", "IOSP",
                            "MLM", "HUN", "SCL", "RS", "MOS", "BERY", "VMC", "AVNT", "RIO", "NEU", "FUL",
                            "IP", "IFF", "ECL", "WRK", "VALE", "VVV", "APD", "LIN", "ARNC", "ASH", "CTVA",
                            "STLD", "SEE", "MP", "NUE", "CF", "CCK", "FMC", "AMCR", "DOW", "GPK", "RPM",
                            "SQM", "SCCO", "GEF", "BCPC", "AVY", "SLGN", "ATR", "CRS", "MUSA", "AG", "LTHM",
                            "KGC", "BALL", "PAAS", "WPM", "UEC", "AEM", "NEM", "RGLD", "NGVT", "LICY"
                           ]

tickers_china = ['3888.HK', '0992.HK', '9868.HK', '1368.HK', '0700.HK', '0881.HK',
                 '2359.HK', '2020.HK', '1810.HK', '2518.HK', '9888.HK', '1929.HK',
                 '6618.HK', '2382.HK', '2333.HK', '0175.HK', '3690.HK', '1024.HK',
                 '2899.HK', '1997.HK', '9626.HK', '2313.HK', '0241.HK', '1171.HK',
                 '6969.HK', '9988.HK', '2238.HK', '2331.HK', '2015.HK', '9999.HK',
                 '0168.HK', '6881.HK', '1299.HK', '1919.HK', '9696.HK', '9618.HK',
                 '0388.HK', '3898.HK', '1044.HK', '0291.HK', '2269.HK', '0960.HK',
                 '0968.HK', '2319.HK', '2196.HK', '0016.HK', '1876.HK', '1066.HK',
                 '0836.HK', '6030.HK', '9633.HK', '2328.HK', '1347.HK', '0101.HK',
                 '2600.HK', '2202.HK', '1378.HK', '0788.HK', '3988.HK', '2007.HK',
                 '0027.HK', '0267.HK', '1288.HK', '6690.HK', '0688.HK', '0001.HK',
                 '1398.HK', '1113.HK', '1928.HK', '2388.HK', '0669.HK', '1038.HK',
                 '3968.HK', '2628.HK', '1177.HK', '0939.HK', '0868.HK', '1336.HK',
                 '0066.HK', '0012.HK', '6862.HK', '1109.HK', '0916.HK', '3908.HK',
                 '3800.HK', '0857.HK', '6185.HK', '6098.HK', '0003.HK', '0338.HK',
                 '0914.HK', '1385.HK', '1093.HK', '0386.HK', '0670.HK', '3692.HK',
                 '1061.HK', '2688.HK', '1099.HK', '2601.HK', '1898.HK', '2883.HK',
                 '1801.HK', '9995.HK', '0268.HK'
                ]

tickers_indexes = ['XU100.IS', '^IBEX', '^IBEX', '^SSMI', '^TECDAX', '^GDAXI', '^IMOEX', '^STOXX',
                     '^RUI', '^FTMC', '^BVSP', '^N225', '^BFX', '^FTSE', '^NDX', '^NYA',
                     '^HSCE', '^NSEI', '^FCHI', '^HSI', '^CASE', '^IXIC', '^DJUSSC', '^DJU',
                     '^DJT', '^DJITR', '^GSPC', '^MID', '^FTLC', '^DJI'
                     'ETRN', 'RIG', 'FCEL'
                  ]

tickers_commodity = ['OUSX', 'FCUSX', 'ZGUSD', 'ZIUSD', 'KWUSX', 'SMUSD', 'SUSX', 'CUSX',
                     'LCUSX', 'BOUSX', 'LHUSX', 'RRUSD', 'PLUSD', 'ZCUSX', 'KEUSX', 'ZOUSX',
                     'NGUSD', 'ZSUSX', 'OJUSX', 'HGUSD', 'GCUSD', 'LBUSD', 'HOUSD', 'CCUSD',
                     'CLUSD', 'KCUSX', 'RBUSD', 'SIUSD', 'CTUSX', 'PAUSD'
                    ]

tickers_allstocks = ["6881.HK", "3898.HK", "1336.HK", "2328.HK", "9868.HK", "3968.HK", "2319.HK",
                     "2318.HK", "1398.HK", "2601.HK", "1088.HK", "2628.HK", "1801.HK", "1038.HK",
                     "1288.HK", "0669.HK", "2518.HK", "6030.HK", "0012.HK", "3988.HK", "0267.HK",
                     "2007.HK", "9888.HK", "9618.HK", "3908.HK", "0939.HK", "0916.HK", "2899.HK", 
                     "2600.HK", "0001.HK", "1093.HK", "2015.HK", "0066.HK", "9999.HK", "9696.HK",
                     "0881.HK", "1061.HK", "1929.HK", "0003.HK", "0016.HK", "1898.HK", "6690.HK",
                     "0288.HK", "6862.HK", "2359.HK", "0688.HK", "0836.HK", "0960.HK", "3690.HK",
                     "9626.HK", "2196.HK", "1368.HK", "2313.HK", "1109.HK", "1810.HK", "2202.HK",
                     "1024.HK", "1113.HK", "1066.HK", "6969.HK", "1378.HK", "3692.HK", "2269.HK",
                     "2020.HK", "0992.HK", "9988.HK", "0027.HK", "2388.HK", "0914.HK", "2331.HK",
                     "1171.HK", "3888.HK", "0101.HK", "0386.HK", "0700.HK", "0338.HK", "0175.HK",
                     "2238.HK", "1876.HK", "2688.HK", "1177.HK", "0670.HK", "0788.HK", "2382.HK",
                     "9633.HK", "6618.HK", "1919.HK", "0857.HK", "6098.HK", "0968.HK", "0241.HK",
                     "0388.HK", "1928.HK", "1099.HK", "0268.HK", "2883.HK", "1044.HK", "2333.HK",
                     "1997.HK", "1299.HK", "6185.HK", "1385.HK", "3800.HK", "0868.HK", "0168.HK",
                     "1347.HK", "0291.HK", "9995.HK", "9866.HK", "9992.HK", "2618.HK", "6865.HK",
                     "1658.HK", "1880.HK", "CC", "MTRN", "AVY", "APD", "CMC", "CCK", "AEM", "WPM",
                     "SLGN", "OI", "GEF", "ARNC", "BERY", "AXTA", "NEM", "ATR", "FCX", "ATI",
                     "MUSA", "LIN", "DOW", "SEE", "CE", "BCC", "RS", "LYB", "CMP", "IP", "DD",
                     "EXP", "SCCO", "FUL", "LAC", "X", "FMC", "WRK", "AMCR", "CLF", "AVNT", "MLM",
                     "MATV", "PAAS", "KGC", "RGLD", "VMC", "ASIX", "MOS", "WLK", "MTX", "ASH",
                     "PPG", "EMN", "HUN", "GPK", "NGVT", "CF", "NEU", "AG", "IFF", "RPM", "IOSP",
                     "SRI", "NTR", "ALB", "BALL", "ECL", "RIO", "VVV", "KALU", "OLN", "CRS", "SHW",
                     "CTVA", "VALE", "AA", "KWR", "SCL", "CBT", "UEC", "LTHM", "SMG", "SQM", "STLD",
                     "MP", "BCPC", "LICY", "NUE", "COP", "SR", "SWX", "CEG", "OGS", "VST", "NFE",
                     "SWN", "VTNR", "BE", "LNG", "OGE", "AMR", "MPC", "ENB", "ET", "ARCH", "TRGP",
                     "EQT", "CTRA", "OKE", "WMB", "CCJ", "ETRN", "ENPH", "SJI", "KMI", "AM", "OVV",
                     "INT", "PSX", "PBA", "TTE", "VLO", "VET", "CLR", "SHEL", "XOM", "CNQ", "CVX",
                     "PDS", "REX", "MGY", "CNX", "PXD", "APA", "EOG", "HES", "BLDP", "OXY", "PBF",
                     "FTI", "SU", "PDCE", "FCEL", "UUUU", "OII", "MRO", "HAL", "HP", "DK", "NOV",
                     "PUMP", "GEVO", "DVN", "CHX", "SLB", "RIG", "BKR", "WHD", "VAL", "OIS", "CLB",
                     "WTTR", "FANG", "MUR", "CTLT", "ARWR", "RARE", "DOCS", "TWST", "LFST", "NTRA",
                     "SKIN", "BMRN", "ENTA", "TXG", "HALO", "RGEN", "PEN", "TFX", "AZTA", "AXNX",
                     "MYGN", "PRTA", "PTCT", "TDOC", "BEAM", "DXCM", "FATE", "CLVT", "SRCL", "GMED",
                     "SYK", "ACAD", "REGN", "INMD", "NBIX", "EVH", "PFE", "HAE", "RDY", "SYNH",
                     "QGEN", "ISRG", "VRTX", "EXEL", "LLY", "NVS", "ABBV", "BMY", "MRK", "HSIC",
                     "TMO", "HOLX", "ITGR", "RMD", "HUM", "ABT", "JNJ", "PGNY", "MDT", "AMGN", "MASI",
                     "EW", "ILMN", "CYTK", "ATRC", "SGEN", "SNY", "CRSP", "BIIB", "OMCL", "NARI",
                     "AMEH", "CORT", "SWAV", "VEEV", "ABCL", "NTLA", "QNST", "BH", "PLUS", "CRNC",
                     "DRQ", "CGNT", "THS", "USNA", "NSSC", "IDCC", "ANF", "HCC", "XNCR", "CPS", "ARRY",
                     "ANDE", "MCRI", "POSH", "ANAB", "EPC", "MFGP", "HZO", "JACK", "SOHU", "CCSI",
                     "ZUO", "BJRI", "NTGR", "MNRO", "VPG", "MGPI", "CHEF", "PI", "SUMO", "GTX", "JBSS",
                     "EAT", "MLNK", "ATNI", "CARS", "UTL", "METC", "BLMN", "PRTS", "OSIS", "RGR",
                     "LRN", "AOUT", "ETD", "CVGW", "FTCI", "HIBB", "JOUT", "ASTS", "MEI", "COHU", 
                     "XPEL", "GPRO", "CEVA", "IRBT", "SPNS", "LEGH", "UCTT", "MHO", "APEI", "PNTG",
                     "EVBG", "STRA", "NABL", "MOMO", "MSEX", "MBUU", "AAN", "FARO", "TAL", "VZIO",
                     "WGO", "AMCX", "OFIX", "BIG", "ATEN", "MOV", "HEAR", "ATEX", "RELY", "GES", "GCO",
                     "PUBM", "SBH", "WW", "MED", "SHEN", "QUOT", "SLP", "DLTH", "BIGC", "CRMT", "YEXT",
                     "ATGE", "PLCE", "RCII", "SLVM", "UDMY", "EGHT", "TLS", "KOPN", "STEM", "WWW",
                     "FNKO", "ZUMZ", "BAND", "QRTEA", "SCSC", "BZUN", "FLWS", "VMEO", "OSTK", "HYLN",
                     "PETQ", "TTMI", "WISH", "BGS", "WKHS", "MVIS", "SNBR", "VLDR", "VUZI", "CLSK",
                     "SKLZ", "DM", "LPSN", "INSG", "CNXN", "AOSL", "SFIX", "TWOU", "CDLX", "TTCF", "BLNK",
                     "VERU", "APPH", "SHOP", "TDC", "ZG", "COIN", "DIOD", "OKTA", "ONTO", "GRMN", "HUBS",
                     "AI", "DBX", "SONY", "DELL", "SNOW", "DOCN", "CGNX", "DT", "TSLA", "NVDA", "QLYS",
                     "ZM", "PLUG", "SEDG", "AMAT", "FORM", "FTNT", "ORCL", "PSN", "AAPL", "BE", "CRWD",
                     "ADI", "MA", "ISRG", "COUP", "MSFT", "LRCX", "TREX", "APP", "APPS", "QRVO", "PANW",
                     "MDB", "AMD", "AEIS", "ASAN", "IT", "PSA", "AMZN", "ABNB", "TTWO", "ADSK", "SNPS",
                     "HOOD", "INTC", "CRM", "V", "TWLO", "MSTR", "KEYS", "ZS", "VMW", "TXN", "PSTG",
                     "ESTC", "BKI", "SPLK", "PRGS", "PYPL", "FISV", "RBLX", "SWKS", "RKLB", "U", "ADP",
                     "NFLX", "FSLR", "IBM", "ROKU", "AZPN", "SQ", "TTD", "DLR", "RIOT", "RPD", "BMBL",
                     "ANSS", "AKAM", "CIEN", "JNPR", "PLTR", "BYND", "UPST", "STX", "MU", "DISH", "NOW",
                     "SNAP", "PAYC", "SDGR", "NET", "QCOM", "ASGN", "ADBE", "PINS", "GTLB", "APPN",
                     "ETSY", "SQSP", "WIX", "PTON", "AYX", "ANET", "EPAM", "UPWK", "SPT", "FSLY", "SSTK"]

tickers_allFMP = tickers_allstocks + tickers_indexes + tickers_commodity

tickers_crypto = ['BTCUSD', 'ETHUSD', 'MATICUSD', 'LINKUSD', 'AVAXUSD', 'TONUSD',
                  'NEARUSD', 'STXUSD', 'FTMUSD', 'THETAUSD', 'C98USD', 'APTUSD',
                  'OPUSD', 'GMXUSD', 'TWTUSD', 'GLMRUSD', 'BLURUSD', 'LPTUSD',
                  'API3USD', 'GTCUSD', 'CFXUSD', 'GRTUSD0', 'DOGEUSD', 'LITUSD0',
                  'CHESSUSD', 'USDTUSD', 'BNBUSD', 'SOLUSD', 'DOTUSD', 'ATOMUSD',
                  'FILUSD', 'VETUSD', 'ALGOUSD', 'QNTUSD', 'EOSUSD', 'MANAUSD',
                  'XTZUSD', 'FLOWUSD', 'RPLUSD', 'CHZUSD', 'KLAYUSD', 'MASKUSD',
                  'KDAUSD', 'BANDUSD', 'CKBUSD', 'REEFUSD', 'STMXUSD', 'OOEUSD',
                  'ARUSD', 'BLZUSD', 'STORJUSD', 'DUSKUSD0', 'IOTXUSD', 'MAGICUSD',
                  'XRPUSD', 'KSMUSD', 'HIVEUSD', 'RLCUSD', 'LDOUSD0', 'NEOUSD',
                  'MDTUSD', 'MOVRUSD', 'FLUXUSD0', 'PHAUSD', 'AUDIOUSD', 'ELFUSD0',
                  'IMXUSD', 'CELOUSD', 'WAVESUSD', 'OCEANUSD', 'LQTYUSD', 'HNTUSD',
                  'TELUSD', 'SKLUSD', 'CELRUSD', 'CHRUSD', 'NFTUSD', 'REQUSD', 
                  'STEEMUSD'
                  ]

tickers_crypto_favourites = ['AERGO-USDT', 'AGIX-USDT', 'AKRO-USDT', 'API3-USDT', 'ARB-USDT', 'ARDR-USDT',
                             'ARK-USDT', 'AR-USDT', 'ASTR-USDT', 'ATOM-USDT', 'AUDIO-USDT', 'AVAX-USDT',
                             'BAND-USDT', 'BIFI-USDT', 'BLZ-USDT', 'BNB-USDT', 'BTC-USDT', 'C98-USDT',
                             'CFX-USDT', 'CHESS-USDT', 'CHR-USDT', 'CHZ-USDT', 'CKB-USDT', 'COS-USDT',
                             'CTSI-USDT', 'CTXC-USDT', 'DATA-USDT', 'DEXE-USDT', 'DF-USDT', 'DGB-USDT',
                             'DOGE-USDT', 'DOT-USDT', 'DUSK-USDT', 'ELF-USDT', 'EOS-USDT', 'ERN-USDT',
                             'ETH-USDT', 'FET-USDT', 'FIL-USDT', 'FLM-USDT', 'FLUX-USDT', 'FTM-USDT',
                             'FTT-USDT', 'GFT-USDT', 'GHST-USDT', 'GLM-USDT', 'GLMR-USDT', 'GMX-USDT',
                             'GRT-USDT', 'GTC-USDT', 'HARD-USDT', 'HIVE-USDT', 'ICP-USDT', 'ICX-USDT',
                             'IMX-USDT', 'IOTX-USDT', 'IQ-USDT', 'KDA-USDT', 'KEY-USDT', 'KSM-USDT',
                             'LDO-USDT', 'LINA-USDT', 'LINK-USDT', 'LIT-USDT', 'LIT-USDT', 'LOOM-USDT',
                             'LRC-USDT', 'LSK-USDT', 'MAGIC-USDT', 'MANA-USDT', 'MATIC-USDT', 'MBL-USDT',
                             'MINA-USDT', 'MOVR-USDT', 'NEAR-USDT', 'NEO-USDT', 'NKN-USDT', 'OCEAN-USDT', 
                             'ONE-USDT', 'OP-USDT', 'OXT-USDT', 'PHA-USDT', 'PHB-USDT', 'PLA-USDT',
                             'QI-USDT', 'QNT-USDT', 'QTUM-USDT', 'RAY-USDT', 'REEF-USDT', 'RLC-USDT',
                             'ROSE-USDT', 'RVN-USDT', 'SCRT-USDT', 'SNM-USDT', 'SOL-USDT', 'STEEM-USDT',
                             'STMX-USDT', 'STORJ-USDT', 'STPT-STX', 'T-USDT', 'THETA-USDT', 'TLM-USDT',
                             'TOMO-USDT', 'TRB-USDT', 'TWT-USDT', 'UTK-USDT', 'VET-USDT', 'VIDT-USDT',
                             'WNXM-USDT', 'XNO-USDT', 'XRP-USDT', 'XTZ-USDT', 'ACE-USDT', 'AIOZ-USDT',
                             'AKRO-USDT', 'AMB-USDT', 'ANT-USDT', 'AVA-USDT', 'BLUR-USDT', 'CEEK-USDT',
                             'CELR-USDT', 'CLV-USDT', 'CUDOS-USDT', 'DAPPT-USDT', 'DAPPX-USDT', 'DC-USDT',
                             'DSLA-USDT', 'EVER-USDT', 'FTG-USDT', 'GEEQ-USDT', 'GGG-USDT', 'GHX-USDT',
                             'GMEE-USDT', 'GRIN-USDT', 'HAPI-USDT', 'HNT-USDT', 'IOI-USDT', 'KAT-USDT',
                             'KOK-USDT', 'LAYER-USDT', 'LIKE-USDT', 'LOOKS-USDT', 'LPT-USDT', 'LYM-USDT',
                             'MAN-USDT', 'MELOS-USDT', 'MITX-USDT', 'MOOV-USDT', 'MTRG-USDT', 'MV-USDT',
                             'NAKA-USDT', 'NOIA-USDT', 'NUM-USDT', 'ONSTON-USDT', 'ONT-USDT', 'OOE-USDT',
                             'ORN-USDT', 'REN-USDT', 'RLY-USDT', 'RMRK-USDT', 'RNDR-USDT', 'SENSO-USDT', 
                             'SHA-USDT', 'SXP-USDT', 'TEL-USDT', 'TLOS-USDT', 'TRVL-USDT', 'TT-USDT',
                             'TVK-USDT', 'UOS-USDT', 'VISION-USDT', 'VXV-USDT', 'WILD-USDT', 'ZKT-USDT'
                            ]

tickers_crypto_KuCoinMain = ["ACH-USDT", "ADA-USDT", "AGIX-USDT", "ALGO-USDT", "APE-USDT", "APT-USDT", "ARB-USDT",
                             "ASTRA-USDT", "ATOM-USDT", "AVAX-USDT", "BCH-USDT", "BTC-USDT", "CFX-USDT", "CRO-USDT",
                             "DOGE-USDT", "DOT-USDT", "DYDX-USDT", "EOS-USDT", "ETC-USDT", "ETH-USDT", "FIL-USDT",
                             "FLUX-USDT", "FTM-USDT", "GALA-USDT", "GMT-USDT", "GRT-USDT", "HBAR-USDT", "HFT-USDT",
                             "ICP-USDT", "IMX-USDT", "INJ-USDT", "JASMY-USDT", "KCS-USDT", "KDA-USDT", "LDO-USDT",
                             "LINK-USDT", "LTC-USDT", "MAGIC-USDT", "MANA-USDT", "MATIC-USDT", "NEAR-USDT", "ONE-USDT",
                             "OP-USDT", "QNT-USDT", "RNDR-USDT", "ROSE-USDT", "SAND-USDT", "SFUND-USDT", "SHIB-USDT",
                             "SNX-USDT", "SOL-USDT", "STX-USDT", "TON-USDT", "TRX-USDT", "UNI-USDT", "USDC-USDT", "VELO-USDT",
                             "VET-USDT", "VRA-USDT", "XCN-USDT", "XLM-USDT", "XMR-USDT", "XRP-USDT", "ZEC-USDT"
                            ]

tickers_crypto_KuCoinOther = ["1INCH-USDT", "2CRZ-USDT", "AAVE-USDT", "ABBC-USDT", "ACA-USDT", "ACE-USDT", "ACOIN-USDT",
                              "ACQ-USDT", "ACS-USDT", "ACT-USDT", "ADS-USDT", "ADX-USDT", "AERGO-USDT", "AFK-USDT",
                              "AGLD-USDT", "AI-USDT", "AIOZ-USDT", "AIPAD-USDT", "AKRO-USDT", "AKT-USDT", "ALEPH-USDT",
                              "ALGO-USDT", "ALICE-USDT", "ALPHA-USDT", "ALPINE-USDT", "ALT-USDT", "AMB-USDT", "AMP-USDT",
                              "AMPL-USDT", "ANC-USDT", "ANKR-USDT", "ANT-USDT", "AOA-USDT", "AOG-USDT", "API3-USDT",
                              "APL-USDT", "AR-USDT", "ARKER-USDT", "ARNM-USDT", "ARPA-USDT", "ARRR-USDT", "ARX-USDT",
                              "ASD-USDT", "ASTR-USDT", "ATA-USDT", "ATOM-USDT", "AUDIO-USDT", "AURORA-USDT", "AURY-USDT",
                              "AVA-USDT", "AXS-USDT", "AZERO-USDT", "BAL-USDT", "BAND-USDT", "BAT-USDT", "BAX-USDT",
                              "BBC-USDT", "BDX-USDT", "BEAT-USDT", "BERPO-USDT", "BFC-USDT", "BICO-USDT", "BIFI-USDT",
                              "BLOK-USDT", "BLUR-USDT", "BLZ-USDT", "BNB-USDT", "BNC-USDT", "BNS-USDT", "BOA-USDT",
                              "BOB-USDT", "BOBA-USDT", "BOLT-USDT", "BOND-USDT", "BONDLY-USDT", "BOSON-USDT", "BRISE-USDT",
                              "BRWL-USDT", "BSV-USDT", "BSW-USDT", "BTT-USDT", "BULL-USDT", "BURGER-USDT", "BUSD-USDT",
                              "BUX-USDT", "BUY-USDT", "C98-USDT", "CAKE-USDT", "CARD-USDT", "CARE-USDT", "CAS-USDT",
                              "CCD-USDT", "CEEK-USDT", "CELO-USDT", "CELR-USDT", "CERE-USDT", "CETUS-USDT", "CFG-USDT",
                              "CGG-USDT", "CGPT-USDT", "CHMB-USDT", "CHR-USDT", "CHZ-USDT", "CIRUS-USDT", "CIX100-USDT",
                              "CKB-USDT", "CLH-USDT", "CLUB-USDT", "CLV-USDT", "CMP-USDT", "COCOS-USDT", "COMP-USDT",
                              "COOHA-USDT", "COTI-USDT", "COV-USDT", "CPOOL-USDT", "CQT-USDT", "CREAM-USDT", "CREDI-USDT",
                              "CRPT-USDT", "CRV-USDT", "CSIX-USDT", "CSPR-USDT", "CTC-USDT", "CTI-USDT", "CTSI-USDT",
                              "CUDOS-USDT", "CULT-USDT", "CVX-USDT", "CWAR-USDT", "CWEB-USDT", "CWS-USDT", "DAG-USDT",
                              "DAO-USDT", "DAPPT-USDT", "DAPPX-USDT", "DAR-USDT", "DASH-USDT", "DATA-USDT", "DC-USDT",
                              "DEGO-USDT", "DERC-USDT", "DERO-USDT", "DEXE-USDT", "DFA-USDT", "DFI-USDT", "DFYN-USDT",
                              "DG-USDT", "DGB-USDT", "DIA-USDT", "DIVI-USDT", "DMTR-USDT", "DODO-USDT", "DOSE-USDT",
                              "DOT-USDT", "DPET-USDT", "DPR-USDT", "DPX-USDT", "DREAMS-USDT", "DSLA-USDT", "DUSK-USDT",
                              "DVPN-USDT", "DYP-USDT", "ECOX-USDT", "EFI-USDT", "EFX-USDT", "EGAME-USDT", "EGLD-USDT",
                              "ELA-USDT", "ELON-USDT", "ENJ-USDT", "ENQ-USDT", "ENS-USDT", "EOSC-USDT", "EPIK-USDT",
                              "EPK-USDT", "EPX-USDT", "EQX-USDT", "EQZ-USDT", "ERG-USDT", "ERN-USDT", "ERSDL-USDT",
                              "ERTHA-USDT", "ETHW-USDT", "ETN-USDT", "EUL-USDT", "EVER-USDT", "EWT-USDT", "FALCONS-USDT",
                              "FCON-USDT", "FEAR-USDT", "FET-USDT", "FIDA-USDT", "FITFI-USDT", "FKX-USDT", "FLAME-USDT",
                              "FLOKI-USDT", "FLOW-USDT", "FLR-USDT", "FLY-USDT", "FORESTPLUS-USDT", "FORM-USDT", "FORT-USDT",
                              "FORTH-USDT", "FRA-USDT", "FRM-USDT", "FRONT-USDT", "FRR-USDT", "FSN-USDT", "FT-USDT",
                              "FTG-USDT", "FTT-USDT", "FXS-USDT", "GAFI-USDT", "GAL-USDT", "GARI-USDT", "GAS-USDT",
                              "GEEQ-USDT", "GEM-USDT", "GENS-USDT", "GFT-USDT", "GGG-USDT", "GHX-USDT", "GLCH-USDT",
                              "GLM-USDT", "GLMR-USDT", "GLQ-USDT", "GMB-USDT", "GMEE-USDT", "GMM-USDT", "GMX-USDT",
                              "GNS-USDT", "GOAL-USDT", "GODS-USDT", "GOVI-USDT", "GPT-USDT", "GRAIL-USDT", "GST-USDT",
                              "GTC-USDT", "H2O-USDT", "H3RO3S-USDT", "HAI-USDT", "HAKA-USDT", "HALO-USDT", "HAPI-USDT",
                              "HARD-USDT", "HAWK-USDT", "HBB-USDT", "HEART-USDT", "HEGIC-USDT", "HERO-USDT", "HIAZUKI-USDT",
                              "HIFI-USDT", "HIGH-USDT", "HIOD-USDT", "HMND-USDT", "HNT-USDT", "HOTCROSS-USDT", "HT-USDT",
                              "HTR-USDT", "HYDRA-USDT", "HYVE", "ICX-USDT", "ID-USDT", "IDEA-USDT", "IGU-USDT", "IHC-USDT",
                              "ILA-USDT", "ILV-USDT", "IOI-USDT", "IOST-USDT", "IOTA-USDT", "IOTX-USDT", "IRON-USDT",
                              "ISP-USDT", "IXS-USDT", "IZI-USDT", "JAM-USDT", "JAR-USDT", "JASMY-USDT", "JST-USDT",
                              "KAGI-USDT", "KAI-USDT", "KAR-USDT", "KARATE-USDT", "KAS-USDT", "KAT-USDT", "KAVA-USDT",
                              "KCS-USDT", "KDA-USDT", "KDON-USDT", "KICKS-USDT", "KING-USDT", "KLAY-USDT", "KLV-USDT",
                              "KMA-USDT", "KMD-USDT", "KNC-USDT", "KOK-USDT", "KOL-USDT", "KONO-USDT", "KRL-USDT", "KSM-USDT",
                              "LABS-USDT", "LACE-USDT", "LADYS-USDT", "LAVAX-USDT", "LAYER-USDT", "LBP-USDT", "LIKE-USDT",
                              "LINA-USDT", "LIT-USDT", "LITH-USDT", "LMR-USDT", "LMWR-USDT", "LOC-USDT", "LOCG-USDT",
                              "LOCUS-USDT", "LOKA-USDT", "LOOKS-USDT", "LPOOL-USDT", "LPT-USDT", "LQTY-USDT", "LRC-USDT",
                              "LSS-USDT", "LTO-USDT", "LTX-USDT", "LYM-USDT", "LYXe-USDT", "MAHA-USDT", "MAKI-USDT",
                              "MAN-USDT", "MAP-USDT", "MARS4-USDT", "MARSH-USDT", "MASK-USDT", "MATTER-USDT", "MBL-USDT",
                              "MC-USDT", "MELOS-USDT", "MEM-USDT", "METIS-USDT", "MINA-USDT", "MIR-USDT", "MITX-USDT",
                              "MJT-USDT", "MKR-USDT", "MLK-USDT", "MLN-USDT", "MLS-USDT", "MNET-USDT", "MNST-USDT",
                              "MNW-USDT", "MODEFI-USDT", "MONI-USDT", "MOOV-USDT", "MOVR-USDT", "MPLX-USDT", "MSWAP-USDT",
                              "MTL-USDT", "MTRG-USDT", "MTS-USDT", "MTV-USDT", "MV-USDT", "MXC-USDT", "MYRIA-USDT",
                              "NAKA-USDT", "NAVI-USDT", "NDAU-USDT", "NEER-USDT", "NEO-USDT", "NFT-USDT", "NGC-USDT",
                              "NGL-USDT", "NHCT-USDT", "NIM-USDT", "NKN-USDT", "NMR-USDT", "NOIA-USDT", "NOM-USDT",
                              "NORD-USDT", "NRFB-USDT", "NTVRK-USDT", "NUM-USDT", "NWC-USDT", "NXRA-USDT", "NYM-USDT",
                              "OAS-USDT", "OCEAN-USDT", "ODDZ-USDT", "OGN-USDT", "OGV-USDT", "OLE-USDT", "OLT-USDT",
                              "OM-USDT", "OMG-USDT", "ONSTON-USDT", "ONT-USDT", "OOE-USDT", "OPCT-USDT", "OPUL-USDT",
                              "ORAI-USDT", "ORBS-USDT", "ORN-USDT", "OSMO-USDT", "OTK-USDT", "OUSD-USDT", "OVR-USDT",
                              "OXEN-USDT", "OXT-USDT", "P00LS-USDT", "PAXG-USDT", "PBR-USDT", "PBX-USDT", "PCX-USDT",
                              "PDEX-USDT", "PEEL-USDT", "PEL-USDT", "PEOPLE-USDT", "PEPE-USDT", "PERP-USDT", "PHA-USDT",
                              "PHNX-USDT", "PIAS-USDT", "PIX-USDT", "PKF-USDT", "PLD-USDT", "PLGR-USDT", "PLU-USDT",
                              "PLY-USDT", "PMON-USDT", "PNT-USDT", "POKT-USDT", "POL-USDT", "POLC-USDT", "POLK-USDT",
                              "POLS-USDT", "POLX-USDT", "POND-USDT", "POSI-USDT", "PRE-USDT", "PRIMAL-USDT", "PRMX-USDT",
                              "PROM-USDT", "PRQ-USDT", "PSL-USDT", "PSTAKE-USDT", "PUMLX-USDT", "PUNDIX-USDT", "PUSH-USDT",
                              "PYR-USDT", "PZP-USDT", "QI-USDT", "QRDO-USDT", "QUARTZ-USDT", "QUICK-USDT", "RACA-USDT",
                              "RACEFI-USDT", "RANKER-USDT", "RBP-USDT", "RDNT-USDT", "REAP-USDT", "RED-USDT", "REEF-USDT",
                              "REN-USDT", "REQ-USDT", "REV-USDT", "REVU-USDT", "REVV-USDT", "RFOX-USDT", "RFUEL-USDT",
                              "RLC-USDT", "RLTM-USDT", "RLY-USDT", "RMRK-USDT", "ROAR-USDT", "ROUTE-USDT", "RPL-USDT",
                              "RSR-USDT", "RUNE-USDT", "RVN-USDT", "SCLP-USDT", "SCRT-USDT", "SD-USDT", "SDAO-USDT",
                              "SDL-USDT", "SENSO-USDT", "SFP-USDT", "SHA-USDT", "SHILL-USDT", "SHR-USDT", "SHX-USDT",
                              "SIDUS-USDT", "SIMP-USDT", "SIN-USDT", "SKEY-USDT", "SKL-USDT", "SKU-USDT", "SLCL-USDT",
                              "SLIM-USDT", "SLP-USDT", "SOLR-USDT", "SOLVE-USDT", "SON-USDT", "SOS-USDT", "SOUL-USDT",
                              "SPA-USDT", "SRBP-USDT", "SRK-USDT", "SRM-USDT", "SSV-USDT", "STARLY-USDT", "STC-USDT",
                              "STEPWATCH-USDT", "STG-USDT", "STND-USDT", "STORE-USDT", "STORJ-USDT", "STRAX-USDT",
                              "STRONG-USDT", "SUI-USDT", "SUIA-USDT", "SUIP-USDT", "SUKU-USDT", "SUN-USDT", "SUPER-USDT",
                              "SUSHI-USDT", "SUTER-USDT", "SWASH-USDT", "SWEAT-USDT", "SWFTC-USDT", "SWINGBY-USDT",
                              "SWP-USDT", "SXP-USDT", "SYLO-USDT", "SYN-USDT", "SYNR-USDT", "SYS-USDT", "T-USDT", "TARA-USDT",
                              "TAUM-USDT", "TEL-USDT", "TEM-USDT", "TFUEL-USDT", "THETA-USDT", "TIDAL-USDT", "TIME-USDT",
                              "TITAN-USDT", "TLM-USDT", "TLOS-USDT", "TOKO-USDT", "TONE-USDT", "TOWER-USDT", "TRAC-USDT",
                              "TRADE-USDT", "TRB-USDT", "TRIAS-USDT", "TRIBE-USDT", "TRIBL-USDT", "TRU-USDT", "TRVL-USDT",
                              "TT-USDT", "TURBOS-USDT", "TVK-USDT", "TWT-USDT", "TXA-USDT", "UBX-USDT", "UFO-USDT",
                              "UMA-USDT", "UNB-USDT", "UNFI-USDT", "UNIC-USDT", "UNO-USDT", "UOS-USDT", "UPO-USDT",
                              "URUS-USDT", "USDD-USDT", "VAI-USDT", "VEED-USDT", "VEGA-USDT", "VEMP-USDT", "VID-USDT",
                              "VIDT-USDT", "VISION-USDT", "VLX-USDT", "VOXEL-USDT", "VR-USDT", "VSYS-USDT", "VXV-USDT",
                              "WAL-USDT", "WAVES-USDT", "WAXL-USDT", "WAXP-USDT", "WELL-USDT", "WEMIX-USDT", "WEST-USDT",
                              "WHALE-USDT", "WILD-USDT", "WIN-USDT", "WLKN-USDT", "WMT-USDT", "WOM-USDT", "WOMBAT-USDT",
                              "WOO-USDT", "WOOP-USDT", "WRX-USDT", "WSIENNA-USDT", "XAVA-USDT", "XCAD-USDT", "XCH-USDT",
                              "XCUR-USDT", "XCV-USDT", "XDB-USDT", "XDC-USDT", "XDEFI-USDT", "XEC-USDT", "XED-USDT",
                              "XEM-USDT", "XETA-USDT", "XHV-USDT", "XNL-USDT", "XNO-USDT", "XPR-USDT", "XPRT-USDT",
                              "XRD-USDT", "XTAG-USDT", "XTM-USDT", "XTZ-USDT", "XWG-USDT", "XYM-USDT", "XYO-USDT",
                              "YFDAI-USDT", "YFI-USDT", "YGG-USDT", "YLD-USDT", "ZBC-USDT", "ZCX-USDT", "ZEE-USDT", 
                              "ZEN-USDT", "ZIL-USDT", "ZKT-USDT", "ZPAY-USDT"
                             ]

tickers_crypto_KuCoinAll = tickers_crypto_KuCoinMain + tickers_crypto_KuCoinOther

